language: android
before_install:
- openssl aes-256-cbc -K $encrypted_dbdccdaa27ba_key -iv $encrypted_dbdccdaa27ba_iv
  -in release.jks.enc -out release.jks -d
- openssl aes-256-cbc -K $encrypted_dbdccdaa27ba_key -iv $encrypted_dbdccdaa27ba_iv
  -in app/src/debug/google-services.json.enc -out app/src/debug/google-services.json -d
- openssl aes-256-cbc -K $encrypted_9880f983d563_key -iv $encrypted_9880f983d563_iv
  -in app/src/release/google-services.json.enc -out app/src/release/google-services.json -d
- yes | sdkmanager "platforms;android-28"
android:
  components:
  - tools
  - platform-tools
  - build-tools-28.0.2
  licenses:
  - android-sdk-license-.+
  - android-sdk-preview-license-.+
deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  api_key:
    secure: lCg63Uv+qgR+OgiwlPEA0HxzNSL60Ph5YjmCFOza2xro2CzCBi4DVtBKOY9MehKN3W0vqBwLe/uDZa7qekEJsbjRETbPdwBZXcnoUnQW5xlEOaahTYw2cVNOqij/3Ipv10qu5DqYJ/MPKwcTh6UoGmYdtgLDL1L7GrnuKHJ1dyNJIlt8XPwy4coivBg8g3p/uLXjSBEXZ3jRBKgQt6oNJ3shflRwj5tL1A3kXWEXp/ZpVa6BOV5GIQYutg1yil4lo88BclJCzEOLd5F/dGRkfI/TxmbzpOqrbuu57duEoEd32lvAZzrt73MI+HPZ+9Ln40kUTkcLM2dp64p5TRNZYR2s67B1bZH+EtulXm0gviXGSryfrgF0wAeYwrTjOXJ9irMRANulFD60kDWWR+qqff/3LFiQSgrPrs3EdkkpiXETK5Bl8MDgXJ8j6LJye6gRdpMqu70JwdYnGYTo+JW9YpM7OU3+T4fdxfKiuc86hf18y1lQptOol2sXNO+0zLskI7Pak1B18Y1j5Eql/4Ey4V1g0QETyPRE6idoUVoI+SRjavcoGY6MfwK1dhzQCG2IWjzr0QNcTU8IHzI4S9m1YwbbKUpkeyPWp+S91smn6cT4gA52b/zOFPry87IaghmZC1xHoPVn4s50b4dyn2XFvSSq38U7apJy5UKWZKhrfGw=
  file_glob: true
  file: "$HOME/build/PSDev/DevDrawer/app/build/outputs/apk/release/*.apk"
  on:
    repo: PSDev/DevDrawer
    tags: true
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
