language: android
before_install:
  - yes | sdkmanager "platforms;android-27"
android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.3
  licenses:
    - 'android-sdk-license-.+'
    - 'android-sdk-preview-license-.+'